### ISSUE TITLE
Upgrade to PostgreSQL 14

### ISSUE THREAD

**Issue by th0rgall** [reallyreadit/db#3]
The currently used version 9.6 has reached [reached end-of-life in November 2021](https://www.postgresql.org/support/versioning/).

Upgrading is a good idea in general but also helps when setting up the development/deployment environment (for example, you now need to install an old version of [Postgress.app](https://postgresapp.com/downloads.html) to be able to run Readup's server with that).

**Comment by jacamera** [comment]
Finally got around to this just this past weekend! The RDS upgrade was a bumpy ride but it appears that none of the existing queries needed to be rewritten (though I haven't tested every single one!). Restoring existing dumps seems to work fine too. For this repo I just updated the README but in the `api` repo you'll want to `dotnet restore` to update a few related packages: https://github.com/reallyreadit/api/commit/a2858713c9c34e771ad64956983497ffb6e2f228

**Comment by th0rgall** [comment]
Great stuff! That's another few years of database longevity :) I unintentionally did the `restore` when setting up my new `api` docker container.
